### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [Vaibhav13kamat/My_portfolio#11]
It would be better if the website have a favicon that relate to your portfolio, I can work on this. Is there anything suitable to be your favicon website portfolio?

**Comment by Vaibhav13kamat** [comment]
![vaibhav kamat (1)](https://user-images.githubusercontent.com/91717908/194015863-3cb297f0-217f-434f-95dd-ccdd6e8bf6f2.png)


sure ...here u go

**Comment by Dimas-Saputra-Me** [comment]
> sure ...here u go

I have made pull request here #15
Let me know if I need to change or add something, thank you.

**Comment by Vaibhav13kamat** [comment]
i will now close this issue
