### ISSUE TITLE
Removing pointer cursor on hovering skills components

### ISSUE THREAD

**Issue by NicoPom** [Vaibhav13kamat/My_portfolio#37]
Hi,

I noticed that on hovering the skills component (html, pyhton, js), the cursor turns into a pointer, as if those elements were clickable. 
I think it's a confusing behavior for the user. 
Would you like to change it ?

**Comment by Vaibhav13kamat** [comment]
sure

**Comment by rohinirai010** [comment]
Please assign me this issue.
