### ISSUE TITLE
Overlap in Mobile View

### ISSUE THREAD

**Issue by shreyaansjain06** [Vaibhav13kamat/My_portfolio#63]
<img width="326" alt="Screenshot 2022-10-10 at 11 29 06 AM" src="https://user-images.githubusercontent.com/86606251/194806014-155fef8f-5aac-421f-b6d9-77af398392d6.png">

Hi there need some fixation in mobile view 
Please assign this issue to me

**Comment by Vaibhav13kamat** [comment]
Ill assign You the Task.
complete #64 #62 #25  also.

**Comment by shreyaansjain06** [comment]
I have made the pr 
Please review it
