### ISSUE TITLE
Adding underline effect on hover over social media icons 

### ISSUE THREAD

**Issue by wickedwisdom0911** [Vaibhav13kamat/My_portfolio#71]
Vaibhav was going through your portfolio , how about adding an underline effect on hovering over social media icons in the footer sectiion.

Here is what it would look like :

![image](https://user-images.githubusercontent.com/78411069/195055046-89a323c7-b9fb-4567-9b39-eb800646c8f9.png)

**Comment by Vaibhav13kamat** [comment]
That would Look Good!!
